# Generated by Django 5.2.1 on 2025-05-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='created_by',
            new_name='user',
        ),
    ]
